# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}-test

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Windows Server 2012 R2

#---------------------------------#
#       build configuration       #
#---------------------------------#

build:
  project: build.proj      # path to Visual Studio solution or project
  
  # MSBuild verbosity level
  verbosity: minimal

# scripts to run after build
#after_build:
#  appveyor PushArtifact \BuildOutput\NuGet\SlowCheetah.*.nupkg

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:

  # pushing a single file
  - path: \BuildOutput\slowcheetah.vsix  
  - path: \BuildOutput\Nuget\slowcheetah.*.nupkg